config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse
from django.contrib import admin
from django.urls import include, path

from photographic.photos.views import ListView as HomeView


def up(request):
    return HttpResponse("Cleared for takeoff!")


urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("settings/", include("photographic.settings.urls")),
    path("photos/", include("photographic.photos.urls")),
    path("users/", include("photographic.users.urls")),
    path("up/", up),
    path("", HomeView.as_view(), name="home")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photographic/photos/urls.py
from django.urls import path

from . import views

app_name = "photos"

urlpatterns = [
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/comment/", views.CreateCommentView.as_view(), name="create_comment"),
    path("create/", views.UploadPhotoView.as_view(), name="create"),
    path("discover/", views.DiscoverView.as_view(), name="discover"),
]

photographic/settings/urls.py
from django.urls import path

from . import views

app_name = "settings"

urlpatterns = [
    path("profile/", views.UpdateProfileView.as_view(), name="profile"),
    path("password/", views.UpdatePasswordView.as_view(), name="password"),
]

photographic/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<slug:slug>/", views.DetailView.as_view(), name="detail"),
    path("<slug:slug>/follow/", views.FollowUserView.as_view(), name="follow_user"),
]

photographic/photos/models.py
from django.conf import settings
from django.db import models


class Photo(models.Model):
    photo = models.ImageField()
    photographer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.photo)


class Comment(models.Model):
    content = models.TextField()
    photo = models.ForeignKey(
        Photo,
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.created_on} {self.author.username} on {self.photo.photo}"

photographic/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from .validators import AlphanumericUsernameValidator


class User(AbstractUser):
    """
    An implementation of a user model with admin-compliant permissions.

    Username and password are required. Other fields are optional.
    """
    username_validator = AlphanumericUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=30,
        unique=True,
        help_text=_('Required. 30 characters or fewer. Letters and digits.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = None
    last_name = None
    email = models.EmailField(
        _('email address'),
        unique=True,
        help_text="Required.",
        error_messages={
            'unique': _("A user with that email address already exists."),
        },
    )

    # from_user_id is followed user
    # to_user_id is follower
    followers = models.ManyToManyField(
        "self",
        related_name="following",
        symmetrical=False
    )

    def clean(self):
        super().clean()
        setattr(self, self.USERNAME_FIELD, self.get_username().lower())

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=120, blank=True)
    photo = models.ImageField(blank=True, upload_to="profile-photos")

photographic/photos/forms.py
from django import forms

from .models import Comment, Photo
from .utils import crop_image


class PhotoForm(forms.Form):
    photo = forms.ImageField()
    caption = forms.CharField(
        required=False,
        widget=forms.Textarea
    )

    def create_photo(self, photographer):
        photo = Photo.objects.create(
            photo=self._get_processed_photo(),
            photographer=photographer
        )

        if self.cleaned_data["caption"]:
            Comment.objects.create(
                content=self.cleaned_data["caption"],
                photo=photo,
                author=photographer
            )

        return photo.id

    def _get_processed_photo(self):
        return crop_image(self.cleaned_data["photo"])

photographic/users/forms.py
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import get_user_model


class UserChangeForm(auth_forms.UserChangeForm):
    class Meta(auth_forms.UserChangeForm.Meta):
        model = get_user_model()


class UserCreationForm(auth_forms.UserCreationForm):
    class Meta(auth_forms.UserCreationForm.Meta):
        model = get_user_model()
        fields = ("username", "email")

photographic/photos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic

from .forms import PhotoForm
from .models import Comment, Photo


class ListView(LoginRequiredMixin, generic.ListView):
    def get_queryset(self):
        following = self.request.user.following.all()
        return Photo.objects.filter(photographer__in=following).order_by("-created_on")[:6]


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Photo

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["comments"] = context["photo"].comment_set.all()
        return context


class CreateCommentView(LoginRequiredMixin, generic.CreateView):
    model = Comment
    fields = ["content"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["photo"] = Photo.objects.get(pk=self.kwargs["pk"])
        return context

    def get_success_url(self):
        photo_id = self.kwargs["pk"]
        return reverse("photos:detail", args=(photo_id,))

    def form_valid(self, form):
        photo = get_object_or_404(Photo, pk=self.kwargs["pk"])

        form.instance.author = self.request.user
        form.instance.photo = photo

        return super().form_valid(form)


class UploadPhotoView(LoginRequiredMixin, generic.FormView):
    form_class = PhotoForm
    template_name = "photos/photo_form.html"

    def form_valid(self, form):
        photo_id = form.create_photo(photographer=self.request.user)
        success_url = reverse("photos:detail", args=(photo_id,))
        return HttpResponseRedirect(success_url)


class DiscoverView(LoginRequiredMixin, generic.ListView):
    queryset = Photo.objects.order_by("-created_on")[:3]

photographic/settings/views.py
from uuid import uuid4

from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse_lazy

from photographic.users.models import Profile


class UpdatePasswordView(LoginRequiredMixin, PasswordChangeView):
    template_name = "settings/password_form.html"
    success_url = reverse_lazy("login")

    def form_valid(self, form):
        form.save()
        logout(self.request)
        return HttpResponseRedirect(self.get_success_url())


class UpdateProfileView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Profile
    fields = ("bio", "photo")
    success_url = reverse_lazy("settings:profile")
    template_name = "settings/profile_form.html"

    def get_object(self, queryset=None):
        return Profile.objects.get(user=self.request.user.id)

    def form_valid(self, form):
        if "photo" in form.changed_data:
            form.instance.photo.name = str(uuid4()) + ".jpg"
        return super().form_valid(form)

photographic/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views import generic
from django.urls import reverse, reverse_lazy

from .forms import UserCreationForm
from .models import User


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = User
    slug_field = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["photo_list"] = context["user"].photo_set.order_by("-created_on")
        context["profile"] = context["user"].profile
        context["is_following"] = self.request.user == context["user"] or self.request.user in context["user"].followers.all()
        return context


class FollowUserView(LoginRequiredMixin, generic.RedirectView):
    def post(self, request, *args, **kwargs):
        user = get_object_or_404(User, username=kwargs["slug"])
        if user.id != request.user.id:
            user.followers.add(request.user)
        return super().post(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        username = self.kwargs["slug"]
        return reverse("users:detail", args=(username,))


class SignUpView(generic.FormView):
    template_name = "users/signup.html"
    form_class = UserCreationForm
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

photographic/templates/photos/comment.html
<li class="comment">
    {% if comment.author.profile.photo %}
        <img src="{{ comment.author.profile.photo.url }}" alt="" class="comment-profile-photo">
    {% else %}
        <div class="comment-avatar"></div>
    {% endif %}
    <p class="comment-content">
        <a href="{% url "users:detail" comment.author.username %}">
            <strong>{{ comment.author.username }}</strong>
        </a>
        {{ comment.content }}
    </p>
    <p class="comment-date">{{ comment.created_on|date:"Y-m-d" }}</p>
</li>

photographic/templates/photos/comment_form.html
{% extends "base_small.html" %}

{% block content %}
<article id="photo-{{ photo.id }}" class="single-photo">
    <div class="photo">
        <img src="{{ photo.photo.url }}" alt="">
    </div>
    <div class="photo-actions">
        <p>
            <a href="{% url "photos:create_comment" photo.id %}">Share a comment</a>
        </p>
        <p class="photo-information">
            {{ photo.photographer.username }} | {{ photo.created_on|date:"Y-m-d" }}
        </p>
    </div>
    <section class="comment-form">
        <form method="post">
            <textarea name="content" cols="40" rows="4" required="" id="id_content" placeholder="Add a comment..." autofocus></textarea>
            {% csrf_token %}
            <p>
                <button type="submit">Comment</button>
            </p>
            <p>
                <a href="{% url "photos:detail" photo.id %}">Back to photo</a>
            </p>
        </form>
    </section>
    <div style="height: 1px;"></div>
</article>
{% endblock %}

photographic/templates/photos/photo_detail.html
{% extends "base_small.html" %}

{% block content %}
<article id="photo-{{ photo.id }}" class="single-photo">
    <div class="photo">
        <img src="{{ photo.photo.url }}" alt="">
    </div>
    <div class="photo-actions">
        <p>
            <a href="{% url "photos:create_comment" photo.id %}">Share a comment</a>
        </p>
        <p class="photo-information">
            {{ photo.photographer.username }} | {{ photo.created_on|date:"Y-m-d" }}
        </p>
    </div>
    <div class="photo-comments">
        <ul>
            {% for comment in comments %}
            {% include "photos/comment.html" with comment=comment only %}
            {% endfor %}
        </ul>
    </div>
    <div style="height: 1px;"></div>
</article>
{% endblock %}

photographic/templates/photos/photo_form.html
{% extends "base_small.html" %}

{% block content %}
<div class="box">
    <form action="{% url "photos:create" %}" method="post" enctype="multipart/form-data">
        <h1>Upload new photo</h1>
        {% csrf_token %}
        {{ form.non_field_errors }}
        <p>
            {{ form.photo.errors }}
            <label for="{{ form.photo.id_for_label }}">Photo</label>
            {{ form.photo }}
        </p>
        <p>
            {{ form.caption.errors }}
            <label for="{{ form.caption.id_for_label }}">Caption</label>
            <textarea name="caption" rows="4" id="{{ form.caption.id_for_label }}"></textarea>
        </p>
        <p>
            <button type="submit">Submit</button>
        </p>
    </form>
</div>
{% endblock %}

photographic/templates/photos/photo_list.html
{% extends "base.html" %}

{% block content %}
<section class="photo-container">
    {% include "photos/photo_list_snippet.html" %}
</section>
{% for photo in photo_list %}
{% empty %}
    <article class="photo-empty">
        <p>Sorry, no photos are available.</p>
    </article>
{% endfor %}
{% endblock %}

photographic/templates/photos/photo_list_snippet.html
{% for photo in photo_list %}
<article class="photo-{{ photo.id }}">
    <a href="{% url "photos:detail" photo.id %}">
        <img src="{{ photo.photo.url }}" alt="">
    </a>
</article>
{% endfor %}